[platformio]
default_envs = waveshare_esp32_s3_lcd_1_9

[env:waveshare_esp32_s3_lcd_1_9]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_build.partitions = huge_app.csv

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

build_src_filter =
  +<*>
  -<servo_gpio42_test.cpp>

lib_deps =
  moononournation/GFX Library for Arduino@1.5.6
  madhephaestus/ESP32Servo@^3.0.6
  bblanchon/ArduinoJson@^6.21.5

[env:servo_gpio42_test]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

build_src_filter =
  -<*>
  +<servo_gpio42_test.cpp>

lib_deps =
  madhephaestus/ESP32Servo@^3.0.6
